### ISSUE TITLE
Removing encrypted file header

### ISSUE THREAD

**Issue by OctaGear** [marcobellaccini/pyAesCrypt#11]
I noticed that an encrypted file gets a header like

> AES  CREATED_BY pyAesCrypt 0.4.3

and I found that it gets added in crypto.py line 165f
and I would like a way to make this optional.

I don't know if removing it would cause issues with decrypting later on but I don't
want anyone to be able to just see what tool was used for the encryption and then
google/search its weaknesses. If that is reasonable.

**Comment by marcobellaccini** [comment]
Hi,
pyAesCrypt has been written to be compatible with the [AES Crypt](https://www.aescrypt.com) [file format](https://www.aescrypt.com/aes_file_format.html) (version 2).
That format includes a header with a mandatory part and some optional extensions.
Hence, I cannot omit that header (at least its mandatory part).
This said, in any case, it's best practice for a file format to contain some versioning information (it's useful for troubleshooting and when newer versions are released).
Moreover, "[security by obscurity](https://en.wikipedia.org/wiki/Security_through_obscurity)" is not considered a valid strategy.

Cheers

Marco
