### ISSUE TITLE
Sans I/O or async  API

### ISSUE THREAD

**Issue by adiroiban** [marcobellaccini/pyAesCrypt#12]
Thanks for working on this implementation.

I wanted to integrate pyAESCrypt with twisted and other async i/o and I ended up with this code

https://gist.github.com/adiroiban/b70f5257b10439c90aaa9dd6f6fda6ca

Let me know if you would like to have async support for this library.

I am happy to send a complete PR with automated tests.

I am not sure about the API...as it was a quick fix.

The structure should be the same...maybe some names should be changed.

For the AESCryptWriter ... we don't really new getHeader ... as it can return the header data together with the first  cal to encryptChunk .... but I prefer to have a separate call for headers.

Also getFooter can be renamed to getFinal or finalize .. to have a similar API naming between crypt and decrypt.

Thanks again!

**Comment by marcobellaccini** [comment]
Hi!
Thank you for sharing your code!
Your contribution is useful indeed, however it seems more like a complete new Python implementation of *AESCrypt* than a *pyAesCrypt* improvement.
For now, I think it would be better to have it in a separate project (and I encourage you to do so).
