### ISSUE TITLE
Decryption of a file in memory without saving to disk

### ISSUE THREAD

**Issue by Salim9304** [marcobellaccini/pyAesCrypt#16]
I encrypted the file using pyAesCrypt.
I want to open and decrypt a file in Python3 and work with it further without saving the decrypted content to disk (work in RAM)

Example:
# decrypt
with open("data.txt.aes", "rb") as fIn:
    encFileSize = stat("data.txt.aes").st_size

    with open("dataout.txt", "wb") as fOut:# NO
        fOut = [] # yes
        pyAesCrypt.decryptStream(fIn, fOut, password, bufferSize, encFileSize)

 print(fOut)
# decrypt data

**Comment by marcobellaccini** [comment]
Hi,
if you want to encrypt/decrypt in-memory, please refer to the 3rd example in the [README file](https://github.com/marcobellaccini/pyAesCrypt/blob/master/README.rst).

Cheers

Marco
