### ISSUE TITLE
How to stop encryption/decryption during process?

### ISSUE THREAD

**Issue by hacker6914** [marcobellaccini/pyAesCrypt#18]
Sir, I want to stop encryption/decryption during process in my project. But I don't know how to do that please help. I don't care if my file get corrupted. I just want to stop encryption/decryption during its process..
Thank u!!!!!!

**Comment by marcobellaccini** [comment]
Hi,
your question is not about _pyAesCrypt_ but about programming in general.
Anyway...
Maybe you can [play with threads](https://stackoverflow.com/questions/323972/is-there-any-way-to-kill-a-thread) (but beware: you're probably trying to do something that a good programmer would disapprove).

**Comment by hacker6914** [comment]
Thank u! So much..
