### ISSUE TITLE
Add PyCharm project settings to .gitignore

### ISSUE THREAD

**Issue by Dead4W** [marcobellaccini/pyAesCrypt#25]
Add folder `.idea` to .gitignore

**Comment by marcobellaccini** [comment]
This is not the right way to exclude editor-related files (although, sometimes, I end up working like that 😅).
There're lots of editors out there and it's poor practice to have a project's gitignore with a gazillion lines for any possible tool.
[This](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) is the way to go.

**Comment by Dead4W** [comment]
I usually use a GitHub Desktop on Windows and sometimes a GitHub bash and didn't about global gitignore. Thanks you!
