### ISSUE TITLE
How to decrypt a encrypted video file into memory using pyAesCrypt

### ISSUE THREAD

**Issue by VinayIsHere** [marcobellaccini/pyAesCrypt#28]
Thanks for this module, Actually I have one encrypt video file and in my player I want to play this video, So can you tell me how can I decrypt the whole video into memory without storing it as a file?
In short I just wanted to know how to read the video file and then decrypt it into memory using ```pyAesCrypt```

**Comment by marcobellaccini** [comment]
Hi,
you can perform in-memory encryption/decryption using BytesIO.
Please check the usage example in the [README](https://github.com/marcobellaccini/pyAesCrypt/blob/master/README.rst).

Cheers

Marco
