### ISSUE TITLE
AES on strings

### ISSUE THREAD

**Issue by Jonahgay** [marcobellaccini/pyAesCrypt#3]
Can you make it, so it deals and encrypts strings instead of files ?

**Comment by marcobellaccini** [comment]
Hi,
pyAesCrypt has been designed to provide a set of functionalities similar to those of the AES Crypt command-line utility.
For this reason, there is no support for raw string encryption.
Nevertheless, having a string encryption function may be useful.
So, I'm labeling your issue as "enhancement".
Maybe I'll add this feature in the next release (of course, I'll have to be careful not to break compatibility with software using current pyAesCrypt module functions).

Thanks for your feedback

Marco

**Comment by marcobellaccini** [comment]
Hi,
pyAesCrypt 0.4 has just been released, featuring support for stream encryption/decryption.
You can check the new usage examples for more information.

Cheers

Marco
