### ISSUE TITLE
how to simultaneously play video while decrypting?[It worked on previous version]

### ISSUE THREAD

**Issue by hacker6914** [marcobellaccini/pyAesCrypt#31]
Hi,with previous version of it i was able to play video files while decrypting a video file.I don't remember that version.Now I am facing problem after reinstalling python and pyAescrypt.
can u say which which version support that thing??
i am getting error,that is** "Moov Atom Not Found"**

**Comment by marcobellaccini** [comment]
Hi,
I don't think this depends on _pyAesCrypt_.

Anyway, if you want, you can try to install the older versions with pip.

Cheers

Marco
