### ISSUE TITLE
Does pyAesCrypt have requirements/dependencies to install?

### ISSUE THREAD

**Issue by taatuut** [marcobellaccini/pyAesCrypt#34]
Hi, I'm happily using pyAesCrypt on Mac OS X and want to install pyAesCrypt on Windows too.

When running below command it fails in the end because it cannot install cryptography (did not include all code, just showing that it collects cryptography). I went through readme and documentation for pyAesCrypt but did not see any requirements/dependencies mentioned.
Is cryptography a requirement or maybe some kind of misconfiguration on my Windows system?

```
c:\bitbucket.org\DataFitness\controloneagent\Tools\Python\PyPy\pypy3.7-v7.3.4-wi
n64>pypy3.exe -m pip install pyAesCrypt
Collecting pyAesCrypt
  Downloading pyAesCrypt-6.0.0-py3-none-any.whl (15 kB)
Collecting cryptography
  Downloading cryptography-3.4.7.tar.gz (546 kB)
     |████████████████████████████████| 546 kB 3.3 MB/s
```

**Comment by marcobellaccini** [comment]
Hi,
as you can see [here](https://www.github.com/marcobellaccini/pyAesCrypt/tree/master/setup.py), pyAesCrypt depends on _pyca/cryptography_.

That dependency should be automatically installed by pip.

It seems like you're using _PyPy_.

While _pyAesCrypt_ is a tiny piece of code and should be able to run fine on that Python implementation, _cryptography_ is a big and complex package and may have problems running on it, especially on Windows (PyPy on Windows seems like a bit exotic to me).

If you can, you may try with the reference Python implementation (CPython).

Cheers

Marco

**Comment by taatuut** [comment]
Hi Marco, thanks for your quick response to my question, and pointing to setup.py. Completely not an pyAesCrypt issue indeed. (As a bit of background info: I have pyAesCrypt and cryptography working with PyPy on Windows now. Picked PyPy for this application to have some kind of an easy deployable Python environment for multiple OS with possibility to install additional modules. Works more or less but bumping into some issues with OpenSSL dependencies.)

**Comment by marcobellaccini** [comment]
Hi Emil,
that's interesting, thank you for the info.

Cheers

Marco
