### ISSUE TITLE
not able to use this please help 

### ISSUE THREAD

**Issue by hd3291** [marcobellaccini/pyAesCrypt#35]
![image](https://user-images.githubusercontent.com/41586271/125208492-67e34080-e2b0-11eb-9b71-11f64e127638.png)

I've not installed this .. I'm directly using .py file from bin folder

**Comment by marcobellaccini** [comment]
Hi,
my best guess is that you've some permissions-related issue.
Please check that you've write permissions for that folder.

Cheers

Marco
