### ISSUE TITLE
Partial decrypt

### ISSUE THREAD

**Issue by brussee** [marcobellaccini/pyAesCrypt#36]
Feature request:

Be able to decrypt a part of the stream, for example part of a very large file.

According to https://stackoverflow.com/a/48833938 it should be possible by a stream.seek(position - 16) to set the IV, then decrypt as normal.

Thanks in advance!

**Comment by marcobellaccini** [comment]
Hi,
thank you for your interest in pyAesCrypt.

Partial decryption is interesting but may be a bit out of scope for this project (pyAesCrypt is intended to be a Python implementation of AES Crypt - see README).

Moreover, it should be noted that an hypothetical partial-decrypt functionality should be implemented preserving HMAC-check (hence, it's not possible to completely "skip" a part of the input stream).

Cheers

Marco
