### ISSUE TITLE
pyaescrypt vs pyarmor

### ISSUE THREAD

**Issue by MyraBaba** [marcobellaccini/pyAesCrypt#37]
Hi,

I would love to get your feedback how we can make more difficult to decrypt encrypted file at hostile docker container ? 

Do you know pyarmor ? How would be the best/bad sides of the both pyaescrypt and pyarmor

**Comment by marcobellaccini** [comment]
Hi,
I'm not sure I understood your question.

Still, I think you can benefit from remembering that:
- [white-box cryptography](https://hackernoon.com/what-is-white-box-cryptography-ph143u5v) is doomed to be insecure
- "security by obscurity" is NOT the way to go
- code obfuscation is usually the wrong answer to the wrong question
- obfuscating Python sounds awkward to most developers

Cheers

Marco

**Comment by MyraBaba** [comment]
@marcobellaccini  thanks for you reply.

Unfortunately I need to send a docker image for a competition and dont trust the counterpart %100. 
I am looking a way to make more harder to reach my source code and the the data which is a AI model .

So I am trying PyaesCrypt and other few docker tricks. 

If you have any suggestion very appreciated.

Best
