### ISSUE TITLE
Does this support string encoding?

### ISSUE THREAD

**Issue by TheStorm135** [marcobellaccini/pyAesCrypt#38]
would i have to make a text file then convert it into a AES file then read it? also  how do i set it to AES-256?
also, for my password, should i just slap my keyboard(not literally) and copying the text it makes as my new password?

**Comment by TheStorm135** [comment]
Can it encrypt photos? And can it encrypt strings?

**Comment by marcobellaccini** [comment]
Hi,
PyAesCrypt supports both file and binary stream encryption/decryption.
Please refer to the README file for all the details.
