### ISSUE TITLE
Input stream valid for pyAesCrypt.decryptStream v6.0.0 causes exception in v6.1.0

### ISSUE THREAD

**Issue by BookWorm0** [marcobellaccini/pyAesCrypt#44]
**Environment**
- OS: macOS Ventura 13.4.1 (c) 
- Python version: 3.11.4
- pip version: 23.2 

**Description**
The attached shell script will first create a /tmp/reprobug directory and subdirectories into which two versions of pyAesCrypt are installed. It will then create a test program and run it using v6.0.0 and v6.1.0 of the package. The test program will encrypt and decrypt its own source code and compare the result to the original source. With the old version of the package, the test passes. With v6.1.0, an exception halts program execution before the decryption occurs.

**Expected behavior**
Test should pass using any version of the package 

**How to Reproduce**
Rename the attached file from reprobug.TXT to reprobug and run "zsh reprobug"
[reprobug.TXT](https://github.com/marcobellaccini/pyAesCrypt/files/12115962/reprobug.TXT)

**Comment by BookWorm0** [comment]
Sorry, please try that with the new attached file, reprobug1.TXT. 

Rename the attached file from reprobug1.TXT to reprobug and run "zsh reprobug"
[reprobug1.TXT](https://github.com/marcobellaccini/pyAesCrypt/files/12116001/reprobug1.TXT)

**Comment by ryanhiebert** [comment]
I'm seeing this behavior as well.

**Comment by BookWorm0** [comment]
@marcobellaccini, it's been a few months since I submitted a pull request (including a unit test) to fix this issue. What else can I do to help get it into the published version of the package?

**Comment by marcobellaccini** [comment]
Sorry for being so late.
Thank you, your PR looks good.

**Comment by marcobellaccini** [comment]
Fixed in Release 6.1.1
