### ISSUE TITLE
Binary Stream On-Demand Processing

### ISSUE THREAD

**Issue by andreaskuster** [marcobellaccini/pyAesCrypt#46]
Hi @marcobellaccini 

First and foremost, thanks a lot for publishing this great library!

For my use case, I use the streaming functionality, processing files of relatively large sizes (MBs to GBs). I figured out that the current stream implementation immediately loads and decrypts the whole stream when calling `decryptStream`. While this is fine for small files, it limits the library usage to files that fit into the available host memory. A more robust approach would be to load and decrypt the amount required by the `read` function on demand.

This code block is responsible for an immediate decryption of the whole payload.
```
`def decryptStream(fIn, fOut, passw, bufferSize=bufferSizeDef, inputLength=None)`
[...]
  # decrypt ciphertext, until last block is reached
  last_block_reached = False
  while not last_block_reached:
      # read data
      cText = fIn.read(bufferSize)

      # end of buffer
      if len(fIn.peek(32 + 1)) < 32 + 1:
          last_block_reached = True
          cText += fIn.read()
          fs16 = cText[-32 - 1]  # plaintext file size mod 16 lsb positions
          hmac0 = cText[-32:]
          cText = cText[: -32 - 1]

      # update HMAC
      hmac0Act.update(cText)
      # decrypt data and write it to output file
      pText = decryptor0.update(cText)

      # remove padding
      if last_block_reached:
          toremove = (16 - fs16) % 16
          if toremove:
              pText = pText[:-toremove]

      fOut.write(pText)
```

A clean solution to this would be to create a file-like reader class implementing the methods `def read(self, size=-1)`, `def tell(self)`  and `def close(self)`, which handles decryption on demand.

I created such an implementation for my project, and if you are interested, I am willing to create a pull request for integration.

**Comment by marcobellaccini** [comment]
Hi,
thank you very much for your interest in _pyAesCrypt_.
Unfortunately, due to lack of time, I've decided to stop accepting PRs for new features (PRs for bugfix are still ok).

If you want to share your code with the community and provide users with new functionalities, of course, feel free to fork the project.

Cheers

Marco
