### ISSUE TITLE
decryptFile shows file permission error when wrong key provided

### ISSUE THREAD

**Issue by sander76** [marcobellaccini/pyAesCrypt#7]
Running windows10 machine

Comparable to https://github.com/marcobellaccini/pyAesCrypt/issues/6

`decryptFile` function throws `FilePermissionError` when wrong key is provided.

possible cause:
https://github.com/marcobellaccini/pyAesCrypt/blob/master/pyAesCrypt/crypto.py#L267

File is being removed while inside `with` block which has the file open.

**Comment by marcobellaccini** [comment]
Thank you!
I've just fixed this!
It was quite unnoticeable on GNU/Linux platforms, yet really annoying on Windows.
I should configure Travis-CI to run tests on Windows too...
