### ISSUE TITLE
Configure Travis-CI to run tests on other OS

### ISSUE THREAD

**Issue by marcobellaccini** [marcobellaccini/pyAesCrypt#8]
Currently, Travis-CI is configured to run tests on GNU/Linux only.

It would be nice (and useful, see https://github.com/marcobellaccini/pyAesCrypt/issues/7) to have tests running on Windows and OS X too.

**Comment by Dead4W** [comment]
PR added #22

**Comment by marcobellaccini** [comment]
Thank you!
The PR has been merged.
I'm closing this.
