### ISSUE TITLE
appended text

### ISSUE THREAD

**Issue by psytron** [marcobellaccini/pyAesCrypt#9]
also would be great to  
 encFileSize = stat("data.txt.aes").st_size 
maybe could be inferred automatically?

**Comment by marcobellaccini** [comment]
Hi,
if you're encrypting/decrypting files, you'll likely want to use the file-oriented functions (that don't require to specify file length).
Check the [README](https://github.com/marcobellaccini/pyAesCrypt/blob/master/README.rst).
